server:
  port: 9001
eureka:
  client:
    registerWithEureka: false #不注册到Eureka,不在注册中心显示
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://www.eureka-7001.com:7001/eureka
feign:
   hystrix:
       enabled: true #开启熔断支持