server:
  port: 7001
eureka:
  instance:
    hostname: www.eureka-7001.com
  client:
    registerWithEureka: false #是否要注册到eureka
    fetchRegistry: false #表示是否从Eureka Server获取注册信息
    serviceUrl:
      defaultZone: http://www.eureka-7001.com:7001/eureka/ #单机配置